version: '3.4'

services:
  tsdockerexample:
    image: tsdockerexample
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
      - 9229:9229
    command: "npm run start:debug"
